package com.headbook.db.mappers;

import com.headbook.db.model.LikesExample;
import com.headbook.db.model.LikesKey;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface LikesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LIKES
     *
     * @mbggenerated
     */
    @SelectProvider(type=LikesSqlProvider.class, method="countByExample")
    int countByExample(LikesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LIKES
     *
     * @mbggenerated
     */
    @DeleteProvider(type=LikesSqlProvider.class, method="deleteByExample")
    int deleteByExample(LikesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LIKES
     *
     * @mbggenerated
     */
    @Delete({
        "delete from LIKES",
        "where user_id = #{userId,jdbcType=BIGINT}",
          "and post_id = #{postId,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(LikesKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LIKES
     *
     * @mbggenerated
     */
    @Insert({
        "insert into LIKES (user_id, post_id)",
        "values (#{userId,jdbcType=BIGINT}, #{postId,jdbcType=BIGINT})"
    })
    int insert(LikesKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LIKES
     *
     * @mbggenerated
     */
    @InsertProvider(type=LikesSqlProvider.class, method="insertSelective")
    int insertSelective(LikesKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LIKES
     *
     * @mbggenerated
     */
    @SelectProvider(type=LikesSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="user_id", property="userId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="post_id", property="postId", jdbcType=JdbcType.BIGINT, id=true)
    })
    List<LikesKey> selectByExample(LikesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LIKES
     *
     * @mbggenerated
     */
    @UpdateProvider(type=LikesSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") LikesKey record, @Param("example") LikesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LIKES
     *
     * @mbggenerated
     */
    @UpdateProvider(type=LikesSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") LikesKey record, @Param("example") LikesExample example);
}