package com.headbook.db.mappers;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

import com.headbook.db.model.Posts;
import com.headbook.db.model.PostsExample;

public interface PostsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POSTS
     *
     * @mbggenerated
     */
    @SelectProvider(type=PostsSqlProvider.class, method="countByExample")
    int countByExample(PostsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POSTS
     *
     * @mbggenerated
     */
    @DeleteProvider(type=PostsSqlProvider.class, method="deleteByExample")
    int deleteByExample(PostsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POSTS
     *
     * @mbggenerated
     */
    @Delete({
        "delete from POSTS",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POSTS
     *
     * @mbggenerated
     */
    @Insert({
        "insert into POSTS (creator, ",
        "date, title, content)",
        "values (#{creator,jdbcType=BIGINT}, ",
        "#{date,jdbcType=TIMESTAMP}, #{title,jdbcType=VARCHAR}, #{content,jdbcType=VARCHAR})"
    })
    @Options(useGeneratedKeys = true, keyProperty="id")
    int insert(Posts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POSTS
     *
     * @mbggenerated
     */
    @InsertProvider(type=PostsSqlProvider.class, method="insertSelective")
    int insertSelective(Posts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POSTS
     *
     * @mbggenerated
     */
    @SelectProvider(type=PostsSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="creator", property="creator", jdbcType=JdbcType.BIGINT),
        @Result(column="date", property="date", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="title", property="title", jdbcType=JdbcType.VARCHAR),
        @Result(column="content", property="content", jdbcType=JdbcType.VARCHAR)
    })
    List<Posts> selectByExample(PostsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POSTS
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, creator, date, title, content",
        "from POSTS",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="creator", property="creator", jdbcType=JdbcType.BIGINT),
        @Result(column="date", property="date", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="title", property="title", jdbcType=JdbcType.VARCHAR),
        @Result(column="content", property="content", jdbcType=JdbcType.VARCHAR)
    })
    Posts selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POSTS
     *
     * @mbggenerated
     */
    @UpdateProvider(type=PostsSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Posts record, @Param("example") PostsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POSTS
     *
     * @mbggenerated
     */
    @UpdateProvider(type=PostsSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Posts record, @Param("example") PostsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POSTS
     *
     * @mbggenerated
     */
    @UpdateProvider(type=PostsSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Posts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POSTS
     *
     * @mbggenerated
     */
    @Update({
        "update POSTS",
        "set creator = #{creator,jdbcType=BIGINT},",
          "date = #{date,jdbcType=TIMESTAMP},",
          "title = #{title,jdbcType=VARCHAR},",
          "content = #{content,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(Posts record);
}