package com.headbook.db.model;

public class LikesKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIKES.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIKES.post_id
     *
     * @mbggenerated
     */
    private Long postId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIKES.user_id
     *
     * @return the value of LIKES.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIKES.user_id
     *
     * @param userId the value for LIKES.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIKES.post_id
     *
     * @return the value of LIKES.post_id
     *
     * @mbggenerated
     */
    public Long getPostId() {
        return postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIKES.post_id
     *
     * @param postId the value for LIKES.post_id
     *
     * @mbggenerated
     */
    public void setPostId(Long postId) {
        this.postId = postId;
    }
}