package com.headbook.db.model;

public class Users {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERS.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERS.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERS.surname
     *
     * @mbggenerated
     */
    private String surname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERS.avatar
     *
     * @mbggenerated
     */
    private String avatar;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERS.id
     *
     * @return the value of USERS.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERS.id
     *
     * @param id the value for USERS.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERS.name
     *
     * @return the value of USERS.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERS.name
     *
     * @param name the value for USERS.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERS.surname
     *
     * @return the value of USERS.surname
     *
     * @mbggenerated
     */
    public String getSurname() {
        return surname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERS.surname
     *
     * @param surname the value for USERS.surname
     *
     * @mbggenerated
     */
    public void setSurname(String surname) {
        this.surname = surname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERS.avatar
     *
     * @return the value of USERS.avatar
     *
     * @mbggenerated
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERS.avatar
     *
     * @param avatar the value for USERS.avatar
     *
     * @mbggenerated
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }
}